import AppKit
import ApplicationServices
import Carbon.HIToolbox

/// Escribe en el portapapeles y, si puede, pega en la app que estaba delante.
@MainActor
public enum Paster {
    /// Una representación lista para volcar al portapapeles.
    public struct Payload: Sendable {
        public let uti: String
        public let data: Data

        public init(uti: String, data: Data) {
            self.uti = uti
            self.data = data
        }
    }

    /// Vuelca **todas** las representaciones en un único `NSPasteboardItem`.
    ///
    /// Escribir solo el texto plano sería más simple y perdería información que
    /// el usuario sí copió: es la app de destino la que debe elegir el formato
    /// que entiende, y solo puede hacerlo si se las ofrecemos todas.
    public static func write(_ payloads: [Payload], to pasteboard: NSPasteboard = .general) {
        guard !payloads.isEmpty else { return }

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        for payload in payloads {
            item.setData(payload.data, forType: NSPasteboard.PasteboardType(payload.uti))
        }
        markAsAutoGenerated(item)
        pasteboard.writeObjects([item])
    }

    /// - Parameter concealed: marca el contenido como sensible.
    ///
    ///   Se usa cuando el destino está en la lista de apps excluidas: mantener el
    ///   texto fuera del historial de Ámbar no basta si se entrega en claro al
    ///   portapapeles del sistema, donde cualquier **otro** gestor lo archivaría.
    ///   `ConcealedType` es la marca que el propio Ámbar honra al leer, así que es la
    ///   que el resto del ecosistema espera.
    public static func writePlainText(
        _ text: String,
        concealed: Bool = false,
        to pasteboard: NSPasteboard = .general
    ) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        markAsAutoGenerated(item)
        if concealed {
            // El literal y no una constante importada: `AppCore` no depende de
            // `ClipboardKit`, donde vive `UTIs.concealed`, y crear esa dependencia por
            // una cadena sería peor. Es la marca de nspasteboard.org, estable.
            item.setData(
                Data(),
                forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
            )
        }
        pasteboard.writeObjects([item])
    }

    /// Marca de nspasteboard.org para contenido escrito por una herramienta y
    /// no por una acción directa de la persona.
    ///
    /// Es cortesía con el resto del ecosistema: si el usuario tiene otro gestor
    /// de portapapeles instalado, esta marca le dice que lo que Ámbar acaba de
    /// poner es un pegado, no una copia nueva, y evita que su historial se
    /// llene de duplicados cada vez que se pega desde aquí.
    private static func markAsAutoGenerated(_ item: NSPasteboardItem) {
        item.setData(
            Data(),
            forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        )
    }

    // MARK: - Pegado

    /// ¿Tiene la app permiso para enviar eventos de teclado?
    public static var canPaste: Bool { AXIsProcessTrusted() }

    /// Abre el panel del sistema que concede el permiso de accesibilidad.
    ///
    /// El diálogo solo aparece una vez por firma de código; después hay que ir
    /// a Ajustes a mano. Por eso la interfaz muestra además un acceso directo.
    @discardableResult
    public static func requestAccessibilityPermission() -> Bool {
        // La constante del SDK (`kAXTrustedCheckOptionPrompt`) es una variable
        // global de C y por tanto no es segura frente a concurrencia bajo
        // Swift 6. Su valor es esta cadena, estable desde OS X 10.9.
        let options = ["AXTrustedCheckOptionPrompt": true]
        return AXIsProcessTrustedWithOptions(options as CFDictionary)
    }

    public static func openAccessibilitySettings() {
        guard let url = URL(
            string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"
        ) else { return }
        NSWorkspace.shared.open(url)
    }

    /// Simula ⌘V en la app que esté en primer plano.
    ///
    /// Requiere el permiso de accesibilidad; sin él el sistema descarta los
    /// eventos en silencio, sin error, así que se comprueba antes y se informa
    /// en la interfaz en vez de fallar de forma invisible.
    @discardableResult
    public static func pasteToFrontmostApp() -> Bool {
        guard canPaste else { return false }
        guard let source = CGEventSource(stateID: .combinedSessionState) else { return false }

        let key = CGKeyCode(kVK_ANSI_V)
        guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        else { return false }

        // Se fija exactamente ⌘ y nada más. Asignar `flags` sobrescribe el
        // estado heredado: si el usuario todavía tiene ⇧ físicamente pulsado
        // del atajo de invocación, sin esto llegaría ⌘⇧V a la app de destino y
        // dispararía otra cosa —«pegar con el mismo estilo», por ejemplo.
        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand

        keyDown.post(tap: .cghidEventTap)
        keyUp.post(tap: .cghidEventTap)
        return true
    }

    /// Espera a que el **foco de teclado** del sistema vuelva a la app indicada.
    ///
    /// POR QUÉ EXISTE, medido: con el panel abierto, la ventana del historial es la ventana
    /// clave del sistema —eso es lo que permite escribir en su campo de búsqueda sin activar la
    /// app, como Spotlight—. Al ocultarla, la app de destino recupera el foco, pero **no en el
    /// mismo instante**: `NSRunningApplication.isActive` ya decía `true` —nunca dejó de estar
    /// activa— y el ⌘V sintético salía antes de que su campo de texto volviera a ser el primer
    /// respondedor. El evento se entregaba y no hacía nada.
    ///
    /// El síntoma exacto: «el permiso está concedido, el contenido llega al portapapeles, no
    /// hay ningún error, y no pega». Verificado con el arnés: el mismo ⌘V posteado sin abrir el
    /// panel pegaba a la primera; posteado después de abrirlo y cerrarlo, se perdía.
    ///
    /// Se **espera al foco real** en lugar de dormir un plazo fijo, por lo mismo que ya decía
    /// `returnFocusToPreviousApplication`: un plazo funciona en la máquina de quien lo escribe
    /// y falla en la del usuario. Esta consulta usa el mismo permiso de accesibilidad que el
    /// pegado, así que no pide nada nuevo.
    public static func waitForKeyboardFocus(
        pid: pid_t,
        timeout: Duration = .milliseconds(600)
    ) async {
        let systemWide = AXUIElementCreateSystemWide()
        let deadline = ContinuousClock.now.advanced(by: timeout)

        while ContinuousClock.now < deadline {
            var value: CFTypeRef?
            if AXUIElementCopyAttributeValue(
                systemWide,
                kAXFocusedApplicationAttribute as CFString,
                &value
            ) == .success, let element = value {
                var focused: pid_t = 0
                let application = unsafeDowncast(element, to: AXUIElement.self)
                if AXUIElementGetPid(application, &focused) == .success, focused == pid {
                    return
                }
            }
            // Short: once the panel leaves the window order the focus is usually back
            // on the first or second look, and every millisecond here is felt.
            try? await Task.sleep(for: .milliseconds(4))
        }
    }

    /// Waits until a key is physically up.
    ///
    /// For keys that trigger a paste. Measured on 2026-10-01: ↵ pasted at 38 ms while
    /// the finger came off the key around 90 ms, after the keyboard had already gone
    /// back to the target app, and that release earned the system beep on every paste
    /// made with the keyboard. Pasting with no key involved was silent. Waiting for the
    /// release keeps the whole keystroke inside the panel, which is also how macOS
    /// buttons respond: on release. Capped, so a key left down cannot hold the paste.
    public static func waitForKeyRelease(
        _ keyCode: CGKeyCode,
        timeout: Duration = .milliseconds(400)
    ) async {
        let deadline = ContinuousClock.now.advanced(by: timeout)
        while ContinuousClock.now < deadline,
              CGEventSource.keyState(.combinedSessionState, key: keyCode) {
            try? await Task.sleep(for: .milliseconds(4))
        }
    }

    /// Espera a que el usuario suelte los modificadores que tenga pulsados.
    ///
    /// El atajo de invocación lleva ⌘ y ⇧. Si se envía el ⌘V sintético mientras
    /// siguen físicamente hundidos, el sistema los combina y la app de destino
    /// recibe una combinación distinta. Con techo, para no quedarse colgado si
    /// alguien deja una tecla apoyada.
    ///
    /// ⌘ is not waited for. The synthetic event IS ⌘V, so a ⌘ still held — the usual
    /// case after ⌘↵, "paste as plain text" — combines into exactly what is posted, and
    /// waiting for it held every plain-text paste until the finger came up.
    public static func waitForModifiersToClear(timeout: Duration = .milliseconds(400)) async {
        let interesting: NSEvent.ModifierFlags = [.shift, .option, .control]
        let deadline = ContinuousClock.now.advanced(by: timeout)

        while ContinuousClock.now < deadline {
            if NSEvent.modifierFlags.intersection(interesting).isEmpty { return }
            try? await Task.sleep(for: .milliseconds(4))
        }
    }
}
